name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY}}
        aws-region: us-east-1
    - name: Build static site
      run: yarn install
    - name: Deploy static site to S3 bucket
      run: aws s3 sync index.html s3://kevincolejr.com --delete